formatter: markdown # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  # TF GCP Compute Instance

  A small, non-standard, Terraform module to deploy a single GCP Compute
  Instance on a schedule for cost optimization.

  {{ .Header }}

  ## Providers

  {{ .Providers }}

  ## Outputs

  {{ .Outputs }}

  include any relative files

  {{ include "relative/path/to/file" }}

  ## Inputs

  {{ .Inputs }}

  ## Examples

  ```hcl
  {{ include "examples/foo/main.tf" }}
  ```

  ## Resources

  {{ range .Module.Resources }}
  - {{ .GetMode }}.{{ .Spec }} ({{ .Position.Filename }}#{{ .Position.Line }})
  {{- end }}

output:
  file: readme.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: true
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: false
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
