machine_type          = "n2d-standard-8"
project_id            = "remote-development-docker"
region                = "us-west1"
service_account_email = "remote-development-docker@remote-development-docker.iam.gserviceaccount.com"
zone                  = "us-west1-c"
